#
#Fri Oct 02 17:14:51 COT 2026
goog\:chromeOptions={args\=[start-maximized, window-size\=1920,1080, disable-infobars, disable-popup-blocking, incognito, start-maximized, window-size\=1920,1080, disable-infobars, disable-popup-blocking, incognito, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=true
browserName=chrome
